version: '3.8'

services:
  mosquitto:
    image: ${DOCKER_REGISTRY-}mosquitto
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    restart: always

  nodered:
    image: ${DOCKER_REGISTRY-}nodered
    build:
      context: .
      dockerfile: nodered/Dockerfile
    depends_on:
      - mosquitto
    restart: always

  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    build:
      context: .
      dockerfile: BreweryFE/Dockerfile
    depends_on:
      - mosquitto
      - nodered
    restart: always
